parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
extends: [airbnb, prettier, prettier/@typescript-eslint, plugin:@typescript-eslint/recommended]
plugins: [prettier]
env:
  browser: true
  node: true
  es6: true
globals:
  graphql: false
rules:
  import/extensions: off
  import/no-extraneous-dependencies: error
  prettier/prettier: error
  react/destructuring-assignment: off
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
  react/no-did-mount-set-state: off
  react/no-unescaped-entities: off
  react/prop-types: off
  react/require-default-props: off
  react/no-unused-state: off
